name: flutterglobal
description: A new Flutter project.

publish_to: "none"

version: 1.1.0+4

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Network & Database
  http: ^0.13.5
  firebase_database: ^9.1.4
  firebase_storage: ^10.3.8
  firebase_core: ^1.22.0
  cloud_firestore: ^3.5.1
  connectivity_plus: ^2.3.7

  # State Management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # Theme & Decoration
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  lottie: ^1.4.3
  flutter_vector_icons: ^1.0.0
  # ios android configurasyonları var
  image_downloader: ^0.31.0
  async_wallpaper: ^2.0.0

  # Cache
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  easy_localization: ^3.0.1

  # Size
  device_preview: ^1.1.0
  another_flushbar: ^1.12.29

  google_mobile_ads: ^2.0.1
  change_app_package_name: ^1.1.0

  collection: ^1.16.0
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/data/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
