// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYoGVEjbWZYwGF9vbOQVe8nH1AYFzDWWU',
    appId: '1:437654232542:android:09a650e71e2169c77ad14f',
    messagingSenderId: '437654232542',
    projectId: 'herseyanime-bf7ec',
    databaseURL: 'https://herseyanime-bf7ec-default-rtdb.firebaseio.com',
    storageBucket: 'herseyanime-bf7ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvaf1hxPZJBS_SG64_ap8FVHD38ejNqdw',
    appId: '1:437654232542:ios:21acd42dd9253d6d7ad14f',
    messagingSenderId: '437654232542',
    projectId: 'herseyanime-bf7ec',
    databaseURL: 'https://herseyanime-bf7ec-default-rtdb.firebaseio.com',
    storageBucket: 'herseyanime-bf7ec.appspot.com',
    iosClientId: '437654232542-e0hpft5n5odvupnf2203rl5urt0qnr0a.apps.googleusercontent.com',
    iosBundleId: 'com.bakapps.herseyanime',
  );
}
